### ISSUE TITLE
ACA-Py JSON-LD capabilities evaluation

### ISSUE THREAD

**Issue by dbluhm** [Indicio-tech/acapy-jsonld-creds-demo#1]
ACA-Py 0.7.0 introduced support for JSON-LD and BBS+ based credentials in the issue-credential 2.0 and present-proof 2.0 protocols. While we have a basic idea of what should be possible with JSON-LD and BBS+ based credentials conceptually, limitations of ACA-Py (such as being unable to store BBS+ keys in the wallet when using Indy as the wallet backend) make support for these credential types more nuanced. Additionally, constructing, issuing, and presenting JSON-LD/BBS+ based credentials differs significantly from issuing Indy AnonCreds using the 1.0 versions of issue-credential and present-proof. We would like to demonstrate usage of these credential types in ACA-Py to get a good feel for changes to the protocols and issuance process, what limitations there are, pain points, and items for future work.

**Comment by dbluhm** [comment]
### Current progress:
Implemented:
- Issue JSON-LD Credential using Ed25519 signature
- Present JSON-LD Credential

Bugs:
- The presented JSON-LD Credential fails to verify. Cause is currently unknown but may have to do with the restrictions in the presentation.

Unimplemented:
- Issue BBS+ Credential (likely requires switching to Askar for wallet backend)
- Present BBS+ Credential (should also require Askar)

**Comment by brycecurtis** [comment]
This issue will be broken into the following tasks:

JSON-LD
- Write a controller in Node.JS
- Issue & verify regular credentials
- Issue JSON-LD credential
- Verify JSON-LD credential

BBS+
- Investigate and learn Askar
- Write a controller in Node.JS or Python
- Issue JSON-LD BBS+ credential
- Verify JSON-LD BBS+ credential

**Comment by dbluhm** [comment]
JSON-LD and BBS+ relevant docs:
- https://github.com/hyperledger/aries-cloudagent-python/blob/main/JsonLdCredentials.md
- https://github.com/hyperledger/aries-rfcs/blob/main/features/0646-bbs-credentials/README.md
- https://github.com/hyperledger/aries-rfcs/blob/main/features/0593-json-ld-cred-attach/README.md

To start ACA-Py using the Askar backend, set the `wallet-type` configuration to `askar`:
```sh
$ aca-py start ... --wallet-type askar
```
Or through yaml config:
```yaml
# ...
wallet-type: askar
# ....
```

```sh
$ aca-py start --arg-file my-config.yml
```

**Comment by chumbert** [comment]
Provisioned and started aca-py with askar backend using:
```
PORTS="8000:8000 8081:8081" ./scripts/run_docker provision \
  --no-ledger -e "http://localhost:8000" \
  --wallet-type askar \
  --wallet-storage-type postgres_storage \
  --wallet-name askar-wallet \
  --wallet-storage-config '{"url": "<db_address>:5432", "wallet_scheme": "MultiWalletSingleTable"}' \
  --wallet-storage-creds '{"account": "postgres", "password": "password", "admin_account": "postgres", "admin_password": "password"}' \
  --recreate-wallet
```
and 
 ```
PORTS="8000:8000 8081:8081" ./scripts/run_docker start \
  --no-ledger -e "http://localhost:8000" \
  -it http 0.0.0.0 8080 \
  -ot http --admin 0.0.0.0 8081 \
  --admin-insecure-mode \
  --wallet-type askar \
  --wallet-storage-type postgres_storage \
  --wallet-name askar-wallet \
  --wallet-storage-config '{"url": "<db_address>:5432", "wallet_scheme": "MultiWalletSingleTable"}' \
  --wallet-storage-creds '{"account": "postgres", "password": "password", "admin_account": "postgres", "admin_password": "password"}' \
  --auto-provision \
  --multitenant \
  --jwt-secret notsosecret
```

**Comment by chumbert** [comment]
Using the acapy demo code and some configuration, it is possible to successfully issue and verify json-ld + bbs+ credentials.

## Config file
Update `demo/demo-arg.yaml` and set 
```yaml
wallet-type: askar
```

this file gets mapped to `/home/indy/demo/demo-args.yaml` in the container. When running the demo containers, set:
```ACAPY_ARG_FILE=/home/indy/demo/demo-args.yaml```
 
## Running the agents
Run the demo for Faber and Alice, setting`--cred-type json-ld` to use JSON-LD with BBS+ credentials and `--events` if you want a detailed log of the callback events received by the controller.

### Faber
```
ACAPY_ARG_FILE=/home/indy/demo/demo-args.yaml ./run_demo faber --cred-type json-ld --events
```

### Alice
```
ACAPY_ARG_FILE=/home/indy/demo/demo-args.yaml ./run_demo alice --events
```

## Scenario
Copy the invitation link from Faber's  screen to Alice's. You can now use the interactive CLI on Faber's  side to issue credentials to Alice and request a credential presentation from Alice.

The events along with their (long) payloads are logged in the console, confirming that credentials and proofs formats are JSON-LD and the crypto suite is BBS+ .

**Comment by chumbert** [comment]
With a few "tricks" (not to say "hacks"), it looks like compound proofs is technically achievable with aca-py. I had to disable a check in `present_proof/dif/pres_exch_handler.py:207`:
```python
                    if issuer_id in cred.subject_ids:
                        filtered_creds_list.append(cred.cred_value)
                    else:
                        raise DIFPresExchError(
                            "Applicable credentials have different credentialSubject.id, "
                            "multiple proofs are not supported currently"
                        )
```
I'm not sure if the exception is raised because of my scenario being ill-defined/implemented or not.

I also had to disable some filtering of the credentials but this is almost certainly an error on my part in the request payload.
